workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          cd $FCI_BUILD_DIR
          gradle wrapper --gradle-version 8.1
      - name: Build APK
        script: |
          cd $FCI_BUILD_DIR
          ./gradlew assembleRelease
      - name: Test
        script: |
          cd $FCI_BUILD_DIR
          ./gradlew test
    artifacts:
      - build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
